Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Jenkins vm  ####
config.vm.define "jenkins" do |jenkins|
  jenkins.vm.box = "ubuntu/jammy64"
  jenkins.vm.hostname = "jenkins"
  jenkins.vm.network "private_network", ip: "192.168.56.11"
  jenkins.vm.network "public_network"
  jenkins.vm.provider "virtualbox" do |vb|
   vb.gui = true
   vb.memory = "2048"
 end
web01.vm.provision "shell", path: "jenkins-setup.sh"   

  end
  
### Nexus vm  #### 
  config.vm.define "nexus" do |nexus|
    nexus.vm.box = "eurolinux-vagrant/centos-stream-9"
    nexus.vm.box_version = "9.0.43"
    nexus.vm.hostname = "nexus"
    nexus.vm.network "private_network", ip: "192.168.56.12"
    nexus.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
    mc01.vm.provision "shell", path: "nexus-setup.sh"  
  end
  
### Sonar vm  ####
config.vm.define "Sonar" do |Sonar|
  Sonar.vm.box = "ubuntu/jammy64"
  Sonar.vm.hostname = "jenkins"
  Sonar.vm.network "private_network", ip: "192.168.56.13"
  Sonar.vm.network "public_network"
  Sonar.vm.provider "virtualbox" do |vb|
   vb.gui = true
   vb.memory = "2048"
 end
web01.vm.provision "shell", path: "sonar-setup.sh" 
  
end
  
end

